### ISSUE TITLE
No class design for Movie

### ISSUE THREAD

**Issue by bpas247** [bpas247/CSS343-Assignment4#2]
The Movie class should have an abstract list of Movie Attributes and an abstract "hash" function (inherited from StoredData) for hashing the index at which to store the object in the Manager class. The Movie class can also be any type of Media, which it should inherit from also.

- [ ] Design the Movie abstract class
- [ ] Design the Comedy Movie ( #13 )
- [ ] Design the Drama Movie ( #14 )
- [ ] Design the Classical Movie ( #15 )
